# ---------------------------------------------------------------------------------------------------------------------
# VARIABLES
# ---------------------------------------------------------------------------------------------------------------------

variable "aws_region" {
  description = "The AWS region to create things in."
}

variable "aws_profile" {
  description = "AWS profile"
}

variable "stack" {
  description = "Name of the stack."
  default     = "mlops-terraform-workshop"
}

variable "vpc_cidr" {
  description = "CIDR for the VPC"
}

variable "az_count" {
  description = "Number of AZs to cover in a given AWS region"
  default     = "2"
}

# variable "aws_ecr" {
#   description = "AWS ECR "
# }

variable "family" {
  description = "Family of the Task Definition"
  default     = "mlops"
}

variable "container_port" {
  description = "Port exposed by the docker image to redirect traffic to"
  default     = 80
}


# name and branch

# variable "source_repo_name" {
#     description = "Source repo name"
#     type = string
# }

# variable "source_repo_branch" {
#     description = "Source repo branch"
#     type = string
# }


# Image repo name for ECR

variable "image_repo_name" {
    description = "Image repo name"
    type = string
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "SSH key-pair generated by Terraform"
}

variable "instance_type" {
  type    =string
  default ="t2.medium"
  description = "Jenkins instance type"
}